# Generated by Django 4.2.1 on 2025-12-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='API固有ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('product_count', models.IntegerField(default=0, verbose_name='関連商品数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '女優',
                'verbose_name_plural': '女優一覧',
                'db_table': 'actress',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('api_source', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='API固有ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('product_count', models.IntegerField(default=0, verbose_name='関連商品数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'シリーズ',
                'verbose_name_plural': 'シリーズ一覧',
                'db_table': 'series',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('api_source', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RawApiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(choices=[('DUGA', 'DUGA API'), ('FANZA', 'FANZA API')], max_length=10, verbose_name='APIソース')),
                ('api_product_id', models.CharField(max_length=255, verbose_name='API商品ID')),
                ('raw_json_data', models.JSONField(verbose_name='生JSONデータ')),
                ('api_service', models.CharField(blank=True, max_length=50, null=True, verbose_name='APIサービスコード')),
                ('api_floor', models.CharField(blank=True, max_length=50, null=True, verbose_name='APIフロアコード')),
                ('migrated', models.BooleanField(default=False, verbose_name='移行済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'API生データ',
                'verbose_name_plural': 'API生データ一覧',
                'db_table': 'raw_api_data',
                'unique_together': {('api_source', 'api_product_id')},
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='API固有ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('product_count', models.IntegerField(default=0, verbose_name='関連商品数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'メーカー',
                'verbose_name_plural': 'メーカー一覧',
                'db_table': 'maker',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('api_source', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LinkshareProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('sku_unique', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='ユニークSKU')),
                ('product_name', models.CharField(blank=True, max_length=2048, null=True, verbose_name='商品名')),
                ('in_stock', models.BooleanField(blank=True, default=True, null=True, verbose_name='在庫')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='有効フラグ')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='通常価格')),
                ('merchant_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='マーチャント名')),
                ('api_source', models.CharField(blank=True, max_length=20, null=True, verbose_name='APIソース')),
                ('raw_csv_data', models.TextField(blank=True, null=True, verbose_name='CSV生データ')),
                ('merchant_id', models.CharField(db_index=True, default='0000', max_length=32, verbose_name='マーチャントID (MID)')),
                ('sku', models.CharField(db_index=True, default='NON-SKU', max_length=256, verbose_name='SKU')),
                ('affiliate_url', models.URLField(blank=True, max_length=2048, null=True, verbose_name='アフィリエイトURL')),
                ('product_url', models.URLField(blank=True, default='', max_length=2048, null=True, verbose_name='商品URL')),
            ],
            options={
                'verbose_name': 'LinkShare商品マスタ',
                'verbose_name_plural': 'LinkShare商品マスタ一覧',
                'db_table': 'normal_product',
                'indexes': [models.Index(fields=['merchant_id', 'updated_at'], name='normal_prod_merchan_f783d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='API固有ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('product_count', models.IntegerField(default=0, verbose_name='関連商品数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'レーベル',
                'verbose_name_plural': 'レーベル一覧',
                'db_table': 'label',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('api_source', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='API固有ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('product_count', models.IntegerField(default=0, verbose_name='関連商品数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ジャンル',
                'verbose_name_plural': 'ジャンル一覧',
                'db_table': 'genre',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('api_source', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='API固有ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('product_count', models.IntegerField(default=0, verbose_name='関連商品数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '監督',
                'verbose_name_plural': '監督一覧',
                'db_table': 'director',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('api_source', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AdultProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_product_id', models.CharField(max_length=255, verbose_name='API提供元製品ID')),
                ('product_id_unique', models.CharField(max_length=255, unique=True, verbose_name='統合ID')),
                ('title', models.CharField(max_length=512, verbose_name='作品タイトル')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='公開日')),
                ('affiliate_url', models.URLField(max_length=2048, verbose_name='アフィリエイトURL')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='販売価格 (円)')),
                ('image_url_list', models.JSONField(default=list, verbose_name='画像URLリスト')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効/無効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('actresses', models.ManyToManyField(related_name='adult_products', to='api.actress', verbose_name='出演者')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adult_products_directed', to='api.director', verbose_name='監督')),
                ('genres', models.ManyToManyField(related_name='adult_products', to='api.genre', verbose_name='ジャンル')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adult_products_labeled', to='api.label', verbose_name='レーベル')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adult_products_made', to='api.maker', verbose_name='メーカー')),
                ('raw_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adult_products', to='api.rawapidata', verbose_name='生データソース')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adult_products_in_series', to='api.series', verbose_name='シリーズ')),
            ],
            options={
                'verbose_name': 'アダルト商品',
                'verbose_name_plural': 'アダルト商品一覧',
                'db_table': 'adult_product',
                'ordering': ['-release_date'],
            },
        ),
    ]
