# Generated by Django 4.2.1 on 2025-11-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawApiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(choices=[('DUGA', 'DUGA API'), ('FANZA', 'FANZA API')], max_length=10, verbose_name='APIソース')),
                ('api_product_id', models.CharField(max_length=255, verbose_name='API商品ID')),
                ('raw_json_data', models.JSONField(verbose_name='生JSONデータ')),
                ('api_service', models.CharField(blank=True, max_length=50, null=True, verbose_name='APIサービスコード')),
                ('api_floor', models.CharField(blank=True, max_length=50, null=True, verbose_name='APIフロアコード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'API生データ',
                'verbose_name_plural': 'API生データ一覧',
                'db_table': 'raw_api_data',
                'unique_together': {('api_source', 'api_product_id')},
            },
        ),
    ]
