# Generated by Django 4.2.1 on 2026-02-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultproduct',
            name='sample_movie_url',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='サンプル動画URL'),
        ),
    ]
