# Generated by Django 4.2.1 on 2025-12-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkshareproduct',
            name='sku_unique',
        ),
        migrations.AddConstraint(
            model_name='linkshareproduct',
            constraint=models.UniqueConstraint(fields=('merchant_id', 'sku'), name='unique_mid_sku_combination'),
        ),
    ]
