# Generated by Django 4.2.1 on 2025-12-20 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='固有ID')),
                ('site_prefix', models.CharField(max_length=20, verbose_name='サイト接頭辞')),
                ('maker', models.CharField(db_index=True, max_length=100, verbose_name='メーカー')),
                ('genre', models.CharField(db_index=True, default='laptop', max_length=50, verbose_name='ジャンル')),
                ('name', models.CharField(max_length=500, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('url', models.URLField(max_length=1000, verbose_name='商品URL')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='画像URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細スペック')),
                ('is_active', models.BooleanField(default=True, verbose_name='掲載中')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'PC製品',
                'verbose_name_plural': 'PC製品一覧',
                'ordering': ['price'],
            },
        ),
    ]
