# Generated by Django 4.2.1 on 2026-05-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='normalized_gpu',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='GPU正規化キー'),
        ),
    ]
