# Generated by Django 4.2.1 on 2025-11-29 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='API固有ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('product_count', models.IntegerField(default=0, verbose_name='関連商品数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '女優',
                'verbose_name_plural': '女優一覧',
                'db_table': 'actress',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('api_source', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='API固有ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('product_count', models.IntegerField(default=0, verbose_name='関連商品数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '監督',
                'verbose_name_plural': '監督一覧',
                'db_table': 'director',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('api_source', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='API固有ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('product_count', models.IntegerField(default=0, verbose_name='関連商品数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ジャンル',
                'verbose_name_plural': 'ジャンル一覧',
                'db_table': 'genre',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('api_source', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='API固有ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('product_count', models.IntegerField(default=0, verbose_name='関連商品数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'レーベル',
                'verbose_name_plural': 'レーベル一覧',
                'db_table': 'label',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('api_source', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='API固有ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('product_count', models.IntegerField(default=0, verbose_name='関連商品数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'メーカー',
                'verbose_name_plural': 'メーカー一覧',
                'db_table': 'maker',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('api_source', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('product_id_unique', models.CharField(max_length=255, unique=True, verbose_name='統合ID')),
                ('title', models.CharField(max_length=512, verbose_name='作品タイトル')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='公開日')),
                ('affiliate_url', models.URLField(max_length=2048, verbose_name='アフィリエイトURL')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='販売価格 (円)')),
                ('image_url_list', models.JSONField(default=list, verbose_name='画像URLリスト')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効/無効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('actresses', models.ManyToManyField(related_name='products', to='api.actress', verbose_name='出演者')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_directed', to='api.director', verbose_name='監督')),
                ('genres', models.ManyToManyField(related_name='products', to='api.genre', verbose_name='ジャンル')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_labeled', to='api.label', verbose_name='レーベル')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_made', to='api.maker', verbose_name='メーカー')),
                ('raw_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.rawapidata', verbose_name='生データソース')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品一覧',
                'db_table': 'product',
                'ordering': ['-release_date'],
            },
        ),
    ]
