# Generated by Django 4.2.1 on 2025-12-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkshareproduct',
            name='sku',
            field=models.CharField(db_index=True, max_length=256, verbose_name='SKU'),
        ),
    ]
