# Generated by Django 4.2.1 on 2025-12-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_linkshareproduct_sku_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkshareApiProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkid', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='LinkShare Link ID')),
                ('mid', models.CharField(db_index=True, max_length=32, verbose_name='広告主ID (MID)')),
                ('api_response_json', models.JSONField(verbose_name='API生JSONデータ')),
                ('sku', models.CharField(db_index=True, default='N/A', max_length=256, verbose_name='SKU/商品コード')),
                ('api_source', models.CharField(default='Linkshare-API-Raw', max_length=50, verbose_name='データソース')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
            ],
            options={
                'verbose_name': 'LinkShare API商品 (生データ)',
                'verbose_name_plural': 'LinkShare API商品一覧 (生データ)',
                'db_table': 'linkshare_api_product',
            },
        ),
    ]
