# Generated by Django 4.2.1 on 2025-12-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_linkshareproduct_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkshareproduct',
            name='link_id',
            field=models.CharField(db_index=True, max_length=128, verbose_name='リンクID'),
        ),
    ]
