# Generated by Django 4.2.1 on 2026-02-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_adultproduct_sample_movie_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_type', models.CharField(choices=[('body', '身体的特徴'), ('style', '作品スタイル'), ('scene', 'シチュエーション'), ('feature', '特殊仕様')], max_length=20, verbose_name='属性タイプ')),
                ('name', models.CharField(max_length=100, verbose_name='表示名')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='スラッグ')),
                ('search_keywords', models.TextField(blank=True, help_text='カンマ(,)区切りで入力', verbose_name='検索キーワード')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
            ],
            options={
                'verbose_name': '作品属性',
                'verbose_name_plural': '作品属性一覧',
                'ordering': ['attr_type', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='ai_content',
            field=models.TextField(blank=True, null=True, verbose_name='AI生成レビュー本文'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='AI記事要約/メタディスクリプション'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='ブログ/SNS投稿済み'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='last_spec_parsed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解析実行日'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_cost',
            field=models.IntegerField(default=0, verbose_name='コスパスコア(1-100)'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_erotic',
            field=models.IntegerField(default=0, verbose_name='エロティシズムスコア(1-100)'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_rarity',
            field=models.IntegerField(default=0, verbose_name='希少性・プレミアスコア(1-100)'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_story',
            field=models.IntegerField(default=0, verbose_name='構成・ストーリースコア(1-100)'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_visual',
            field=models.IntegerField(default=0, verbose_name='ルックス・画質スコ2(1-100)'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='spec_score',
            field=models.IntegerField(default=0, verbose_name='総合評価スコア(0-100)'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='target_segment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AI判定ターゲット層'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='掲載中'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.adultattribute', verbose_name='詳細スペック属性'),
        ),
    ]
