# Generated by Django 4.2.1 on 2026-05-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pcproduct_normalized_gpu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcattribute',
            name='is_adult',
        ),
        migrations.AddField(
            model_name='pcattribute',
            name='color',
            field=models.CharField(blank=True, default='', help_text='frontend semantic color', max_length=50, verbose_name='表示カラー'),
        ),
        migrations.AddField(
            model_name='pcattribute',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='frontend icon key', max_length=50, verbose_name='表示アイコン'),
        ),
        migrations.AddField(
            model_name='pcattribute',
            name='semantic_role',
            field=models.CharField(blank=True, default='', help_text='primary / secondary / highlight など', max_length=50, verbose_name='セマンティック役割'),
        ),
        migrations.AddField(
            model_name='pcattribute',
            name='semantic_weight',
            field=models.FloatField(default=0, help_text='0.0 - 1.0', verbose_name='セマンティック重要度'),
        ),
    ]
