# Generated by Django 4.2.1 on 2025-12-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pcproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcproduct',
            name='genre',
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='raw_genre',
            field=models.CharField(default='', max_length=100, verbose_name='サイト別分類'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='unified_genre',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='統合ジャンル'),
        ),
    ]
