# Generated by Django 4.2.1 on 2025-11-29 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_actress_director_genre_label_maker_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='API固有ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('product_count', models.IntegerField(default=0, verbose_name='関連商品数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'シリーズ',
                'verbose_name_plural': 'シリーズ一覧',
                'db_table': 'series',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('api_source', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_in_series', to='api.series', verbose_name='シリーズ'),
        ),
    ]
