# Generated by Django 4.2.1 on 2026-05-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_pcattribute_is_adult_pcattribute_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='weight_kg',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='重量(kg)'),
        ),
    ]
