# Generated by Django 4.2.1 on 2025-11-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_series_product_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawapidata',
            name='migrated',
            field=models.BooleanField(default=False, verbose_name='移行済み'),
        ),
    ]
