# Generated by Django 4.2.1 on 2025-12-08 14:33
# 🚨 以下の内容に置き換えてください 🚨

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        # 依存関係はそのまま
        ('api', '0003_alter_linkshareproduct_link_id'),
    ]

    # **このリストを空にすることで、Djangoに「このマイグレーションでは何も操作しない」と伝えます**
    operations = [
        
    ]