# Generated by Django 4.2.1 on 2025-12-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_pcproduct_genre_pcproduct_raw_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='raw_html',
            field=models.TextField(blank=True, null=True, verbose_name='生のHTML内容'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='stock_status',
            field=models.CharField(default='在庫あり', max_length=100, verbose_name='在庫/受注状況'),
        ),
    ]
