# Generated by Django 4.2.1 on 2025-12-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_linkshareapiproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkshareapiproduct',
            name='linkid',
            field=models.CharField(db_index=True, max_length=255, verbose_name='LinkShare Link ID'),
        ),
        migrations.AddConstraint(
            model_name='linkshareapiproduct',
            constraint=models.UniqueConstraint(fields=('linkid', 'mid'), name='unique_linkid_mid'),
        ),
    ]
