# Generated by Django 4.2.1 on 2026-02-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_adultattribute_adultproduct_ai_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultproduct',
            name='sample_movie_url',
            field=models.JSONField(blank=True, help_text="{'url': '...', 'preview_image': '...'} の形式で格納", null=True, verbose_name='サンプル動画データ'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='score_visual',
            field=models.IntegerField(default=0, verbose_name='ルックス・画質スコア(1-100)'),
        ),
    ]
