# Generated by Django 4.2.1 on 2025-12-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20251208_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkshareproduct',
            name='availability',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='在庫情報'),
        ),
        migrations.AlterField(
            model_name='linkshareproduct',
            name='manufacturer_part_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='製造品番'),
        ),
        migrations.AlterField(
            model_name='linkshareproduct',
            name='product_name',
            field=models.CharField(max_length=512, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='linkshareproduct',
            name='product_url',
            field=models.URLField(max_length=2048, verbose_name='商品URL'),
        ),
    ]
