# Generated by Django 5.2.8 on 2025-12-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rawapidata_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='api_product_id',
            field=models.CharField(default='UNKNOWN', max_length=255, verbose_name='API提供元製品ID'),
            preserve_default=False,
        ),
    ]
