# Generated by Django 4.2.1 on 2026-02-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_adultproduct_sample_movie_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultproduct',
            name='product_description',
            field=models.TextField(blank=True, help_text='DUGAのcaptionやFANZAのreview等、AI解析の元ネタとなる文章', null=True, verbose_name='作品紹介文'),
        ),
    ]
