# Generated by Django 4.2.1 on 2025-12-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pcproduct_raw_html_pcproduct_stock_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcLinkshareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkid', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='リンクID')),
                ('mid', models.CharField(db_index=True, max_length=32, verbose_name='マーチャントID')),
                ('merchant_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='マーチャント名')),
                ('product_name', models.CharField(blank=True, max_length=2048, null=True, verbose_name='商品名')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='SKU')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='価格')),
                ('product_url', models.URLField(blank=True, max_length=2048, null=True, verbose_name='商品URL')),
                ('affiliate_url', models.URLField(blank=True, max_length=2048, null=True, verbose_name='アフィリエイトURL')),
                ('image_url', models.URLField(blank=True, max_length=2048, null=True, verbose_name='画像URL')),
                ('api_response_json', models.JSONField(verbose_name='APIレスポンス生データ')),
                ('api_source', models.CharField(default='Linkshare-BC-API', max_length=50, verbose_name='取得ソース')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'BC LinkShare商品',
                'verbose_name_plural': 'BC LinkShare商品一覧',
                'db_table': 'bc_linkshare_product',
                'indexes': [models.Index(fields=['mid', 'updated_at'], name='bc_linkshar_mid_9fc287_idx')],
            },
        ),
    ]
