# Generated by Django 4.2.1 on 2026-05-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pcproduct_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcattribute',
            name='attr_type',
            field=models.CharField(choices=[('cpu', 'CPU'), ('memory', 'メモリ'), ('storage', 'ストレージ'), ('gpu', 'GPU'), ('maker', 'メーカー'), ('usage', '用途'), ('pc_feature', 'PC特徴'), ('display', 'ディスプレイ'), ('resolution', '解像度'), ('refresh_rate', 'リフレッシュレート'), ('panel_type', 'パネル種別'), ('npu', 'AIプロセッサ(NPU)'), ('os', 'OS'), ('software', 'ソフトウェア種別'), ('license', 'ライセンス形態')], max_length=20, verbose_name='属性タイプ'),
        ),
        migrations.AlterField(
            model_name='pcattribute',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='数字が小さいほど上', verbose_name='並び順'),
        ),
        migrations.AlterField(
            model_name='pcattribute',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='検索時に使用する別名です。複数の場合はカンマ区切り。', verbose_name='検索キーワード'),
        ),
        migrations.AlterField(
            model_name='pcattribute',
            name='semantic_role',
            field=models.CharField(blank=True, default='', help_text='primary / secondary / highlight / brand', max_length=50, verbose_name='セマンティック役割'),
        ),
    ]
