# Generated by Django 4.2.1 on 2025-12-06 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_api_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_product_id', models.CharField(max_length=255, verbose_name='API提供元製品ID')),
                ('product_id_unique', models.CharField(max_length=255, unique=True, verbose_name='統合ID')),
                ('title', models.CharField(max_length=512, verbose_name='作品タイトル')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='公開日')),
                ('affiliate_url', models.URLField(max_length=2048, verbose_name='アフィリエイトURL')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='販売価格 (円)')),
                ('image_url_list', models.JSONField(default=list, verbose_name='画像URLリスト')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効/無効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('actresses', models.ManyToManyField(related_name='adult_products', to='api.actress', verbose_name='出演者')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adult_products_directed', to='api.director', verbose_name='監督')),
                ('genres', models.ManyToManyField(related_name='adult_products', to='api.genre', verbose_name='ジャンル')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adult_products_labeled', to='api.label', verbose_name='レーベル')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adult_products_made', to='api.maker', verbose_name='メーカー')),
                ('raw_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adult_products', to='api.rawapidata', verbose_name='生データソース')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adult_products_in_series', to='api.series', verbose_name='シリーズ')),
            ],
            options={
                'verbose_name': 'アダルト商品',
                'verbose_name_plural': 'アダルト商品一覧',
                'db_table': 'adult_product',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='NormalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(default='LINKSHARE', max_length=20, verbose_name='APIソース')),
                ('sku_unique', models.CharField(max_length=255, unique=True, verbose_name='SKU/統合ID')),
                ('title', models.CharField(max_length=512, verbose_name='商品名')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='販売価格 (円)')),
                ('in_stock', models.BooleanField(default=True, verbose_name='在庫あり')),
                ('affiliate_url', models.URLField(max_length=2048, verbose_name='アフィリエイトURL')),
                ('image_url', models.URLField(max_length=2048, verbose_name='メイン画像URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効/無効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ノーマル商品',
                'verbose_name_plural': 'ノーマル商品一覧',
                'db_table': 'normal_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
