# Generated by Django 4.2.1 on 2026-02-08 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_adultproduct_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(max_length=10, verbose_name='APIソース (DUGA/FANZA)')),
                ('api_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='API固有ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('ruby', models.CharField(blank=True, max_length=255, null=True, verbose_name='ふりがな')),
                ('product_count', models.IntegerField(default=0, verbose_name='関連商品数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '著者',
                'verbose_name_plural': '著者一覧',
                'db_table': 'author',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('api_source', 'name')},
            },
        ),
        migrations.AddField(
            model_name='actress',
            name='ruby',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ふりがな'),
        ),
        migrations.AddField(
            model_name='director',
            name='ruby',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ふりがな'),
        ),
        migrations.AddField(
            model_name='genre',
            name='ruby',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ふりがな'),
        ),
        migrations.AddField(
            model_name='label',
            name='ruby',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ふりがな'),
        ),
        migrations.AddField(
            model_name='maker',
            name='ruby',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ふりがな'),
        ),
        migrations.AddField(
            model_name='series',
            name='ruby',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ふりがな'),
        ),
        migrations.CreateModel(
            name='FanzaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255, unique=True, verbose_name='統合用ID')),
                ('content_id', models.CharField(db_index=True, max_length=100, verbose_name='コンテンツID')),
                ('product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='プロダクトID')),
                ('site_code', models.CharField(db_index=True, max_length=20, verbose_name='サイト')),
                ('service_code', models.CharField(db_index=True, max_length=50, verbose_name='サービス')),
                ('floor_code', models.CharField(db_index=True, max_length=50, verbose_name='フロア')),
                ('floor_name', models.CharField(blank=True, max_length=100, verbose_name='フロア名')),
                ('title', models.CharField(max_length=512, verbose_name='タイトル')),
                ('url', models.URLField(max_length=1000, verbose_name='商品URL')),
                ('affiliate_url', models.URLField(max_length=2048, verbose_name='アフィURL')),
                ('release_date', models.DateTimeField(db_index=True, null=True, verbose_name='発売・配信日')),
                ('volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='ボリューム/収録時間')),
                ('price_info', models.JSONField(default=dict, verbose_name='価格情報')),
                ('review_count', models.IntegerField(default=0, verbose_name='レビュー数')),
                ('review_average', models.FloatField(default=0.0, verbose_name='レビュー平均点')),
                ('image_urls', models.JSONField(default=dict, verbose_name='画像URLリスト')),
                ('sample_images', models.JSONField(default=list, verbose_name='サンプル画像リスト')),
                ('sample_movie', models.JSONField(blank=True, default=dict, null=True, verbose_name='サンプル動画データ')),
                ('raw_item_info', models.JSONField(default=dict, verbose_name='API生情報(item_info)')),
                ('product_description', models.TextField(blank=True, verbose_name='作品紹介/レビュー文')),
                ('ai_summary', models.CharField(blank=True, max_length=500, verbose_name='AI要約')),
                ('score_visual', models.IntegerField(default=0, verbose_name='ルックス点')),
                ('score_story', models.IntegerField(default=0, verbose_name='ストーリー点')),
                ('score_cost', models.IntegerField(default=0, verbose_name='コスパ点')),
                ('score_erotic', models.IntegerField(default=0, verbose_name='エロ点')),
                ('score_rarity', models.IntegerField(default=0, verbose_name='プレミア点')),
                ('radar_chart_data', models.JSONField(default=list, verbose_name='チャート用JSON')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開フラグ')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='おすすめフラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actresses', models.ManyToManyField(related_name='fanza_products', to='api.actress')),
                ('authors', models.ManyToManyField(blank=True, related_name='fanza_products', to='api.author')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fanza_products', to='api.director')),
                ('genres', models.ManyToManyField(related_name='fanza_products', to='api.genre')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fanza_products', to='api.label')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fanza_products', to='api.maker')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fanza_products', to='api.series')),
            ],
            options={
                'verbose_name': 'FANZA商品',
                'verbose_name_plural': 'FANZA商品一覧',
                'db_table': 'fanza_product',
                'ordering': ['-release_date'],
                'indexes': [models.Index(fields=['unique_id'], name='fanza_produ_unique__b5b3bf_idx'), models.Index(fields=['content_id'], name='fanza_produ_content_11a9d1_idx'), models.Index(fields=['site_code', 'service_code', 'floor_code'], name='fanza_produ_site_co_c3342e_idx'), models.Index(fields=['release_date'], name='fanza_produ_release_5fbc9e_idx'), models.Index(fields=['is_active'], name='fanza_produ_is_acti_b574d0_idx')],
            },
        ),
    ]
