# Generated by Django 4.2.1 on 2026-05-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pcattribute_attr_type_alter_pcattribute_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcattribute',
            name='is_adult',
            field=models.BooleanField(db_index=True, default=False, help_text='共通 semantic TSV 用。通常のPC属性は False。', verbose_name='アダルト属性フラグ'),
        ),
    ]
