# Generated by Django 4.2.1 on 2025-12-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_linkshareproduct_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkshareproduct',
            name='product_url',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='商品URL'),
        ),
    ]
