# Generated by Django 4.2.1 on 2026-01-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bclinkshareproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='WP投稿済み'),
        ),
    ]
