# Generated by Django 4.2.1 on 2026-01-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pcproduct_is_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='ai_content',
            field=models.TextField(blank=True, null=True, verbose_name='AI生成記事本文'),
        ),
    ]
