# Generated by Django 4.2.1 on 2026-05-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pcattribute_is_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcattribute',
            name='is_ranking_enabled',
            field=models.BooleanField(default=False, help_text='semantic ranking endpoint 対象属性', verbose_name='ランキング対象'),
        ),
    ]
