# Generated by Django 4.2.1 on 2026-02-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_author_actress_ruby_director_ruby_genre_ruby_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actress',
            unique_together={('api_source', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('api_source', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='director',
            unique_together={('api_source', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('api_source', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('api_source', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='maker',
            unique_together={('api_source', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together={('api_source', 'name')},
        ),
        migrations.AddField(
            model_name='actress',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AddField(
            model_name='director',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AddField(
            model_name='label',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AddField(
            model_name='maker',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AlterUniqueTogether(
            name='actress',
            unique_together={('api_source', 'slug'), ('api_source', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('api_source', 'slug'), ('api_source', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='director',
            unique_together={('api_source', 'slug'), ('api_source', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('api_source', 'slug'), ('api_source', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('api_source', 'slug'), ('api_source', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='maker',
            unique_together={('api_source', 'slug'), ('api_source', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together={('api_source', 'slug'), ('api_source', 'name')},
        ),
    ]
