# Generated by Django 4.2.1 on 2026-02-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_actress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='director',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='label',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
    ]
