# Generated by Django 4.2.1 on 2026-01-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pcproduct_ai_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='affiliate_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='アフィリエイトURL最終更新'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='affiliate_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='正式アフィリエイトURL'),
        ),
    ]
