# Generated by Django 4.2.1 on 2026-05-15 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pcattribute_is_ranking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultattribute',
            name='color',
            field=models.CharField(blank=True, default='', help_text='frontend semantic color token', max_length=50, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='adultattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adultattribute',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='frontend semantic icon key', max_length=100, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='adultattribute',
            name='is_ranking_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='ranking runtime eligibility', verbose_name='ランキング有効'),
        ),
        migrations.AddField(
            model_name='adultattribute',
            name='semantic_role',
            field=models.CharField(blank=True, db_index=True, default='', help_text='semantic runtime role (ranking / finder / seo / related / concierge)', max_length=100, verbose_name='Semantic Role'),
        ),
        migrations.AddField(
            model_name='adultattribute',
            name='semantic_weight',
            field=models.FloatField(default=1.0, help_text='semantic ranking/discovery weight', verbose_name='Semantic Weight'),
        ),
        migrations.AddField(
            model_name='adultattribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='is_adult',
            field=models.BooleanField(db_index=True, default=True, help_text='True固定。PC semantic authority と混在しないためのドメイン識別', verbose_name='アダルト属性フラグ'),
        ),
        migrations.AddIndex(
            model_name='adultattribute',
            index=models.Index(fields=['attr_type', 'order'], name='adult_attri_attr_ty_34343d_idx'),
        ),
        migrations.AddIndex(
            model_name='adultattribute',
            index=models.Index(fields=['semantic_role'], name='adult_attri_semanti_63b244_idx'),
        ),
        migrations.AddIndex(
            model_name='adultattribute',
            index=models.Index(fields=['is_ranking_enabled'], name='adult_attri_is_rank_c6659d_idx'),
        ),
        migrations.AddIndex(
            model_name='adultattribute',
            index=models.Index(fields=['slug'], name='adult_attri_slug_978f5e_idx'),
        ),
        migrations.AlterModelTable(
            name='adultattribute',
            table='adult_attribute',
        ),
    ]
