# Generated by Django 4.2.1 on 2026-05-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_adultattribute_color_adultattribute_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='product_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='semantic_runtime',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='semantic_score',
            field=models.FloatField(default=0),
        ),
    ]
