# Generated by Django 4.2.1 on 2026-01-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pcproduct_affiliate_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_type', models.CharField(choices=[('cpu', 'CPU'), ('memory', 'メモリ'), ('storage', 'ストレージ'), ('gpu', 'グラフィック'), ('npu', 'AIプロセッサ(NPU)'), ('os', 'OS')], max_length=20, verbose_name='属性タイプ')),
                ('name', models.CharField(max_length=100, verbose_name='表示名')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='スラッグ')),
            ],
            options={
                'verbose_name': 'スペック属性',
                'verbose_name_plural': 'スペック属性一覧',
            },
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.pcattribute', verbose_name='スペック属性タグ'),
        ),
    ]
