# Generated by Django 4.2.1 on 2026-02-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_actress_slug_alter_author_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='slug',
            field=models.CharField(db_index=True, help_text='URLに使用されます。日本語可。', max_length=100, unique=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='director',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='label',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='スラッグ'),
        ),
    ]
