# Generated by Django 4.2.1 on 2026-01-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pcattribute_pcproduct_attributes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcattribute',
            options={'ordering': ['attr_type', 'order', 'name'], 'verbose_name': 'スペック属性', 'verbose_name_plural': 'スペック属性一覧'},
        ),
        migrations.AlterModelOptions(
            name='pcproduct',
            options={'ordering': ['-updated_at'], 'verbose_name': 'PC製品', 'verbose_name_plural': 'PC製品一覧'},
        ),
        migrations.AddField(
            model_name='pcattribute',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='数字が小さいほど上に表示されます', verbose_name='並び順'),
        ),
    ]
