# Generated by Django 4.2.1 on 2026-05-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pcproduct_product_type_pcproduct_semantic_runtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='runtime_profiles',
            field=models.JSONField(blank=True, default=list, verbose_name='Runtime Profiles'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='semantic_labels',
            field=models.JSONField(blank=True, default=list, verbose_name='Semantic Labels'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='semantic_runtime_compiled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Semantic Runtime Compiled'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='semantic_schema_version',
            field=models.CharField(db_index=True, default='v3', max_length=20, verbose_name='Semantic Schema Version'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='semantic_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Semantic Updated At'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='workflow_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Workflow Tags'),
        ),
    ]
