# Generated by Django 4.2.1 on 2026-02-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_actress_slug_alter_adultattribute_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanzaproduct',
            name='price',
            field=models.IntegerField(db_index=True, default=0, verbose_name='基本価格'),
        ),
        migrations.AlterField(
            model_name='fanzaproduct',
            name='price_info',
            field=models.JSONField(default=dict, verbose_name='詳細価格情報'),
        ),
        migrations.AddIndex(
            model_name='fanzaproduct',
            index=models.Index(fields=['price'], name='fanza_produ_price_32d375_idx'),
        ),
    ]
