# Generated by Django 4.2.1 on 2026-06-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_pcproduct_runtime_profiles_pcproduct_semantic_labels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('product_id_unique', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('image_status', models.CharField(db_index=True, default='unknown', max_length=50)),
                ('image_valid', models.BooleanField(default=False)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
