# Generated by Django 4.2.1 on 2026-02-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_fanzaproduct_price_alter_fanzaproduct_price_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultproduct',
            name='api_source',
            field=models.CharField(help_text='取得元のプラットフォーム識別子', max_length=20, verbose_name='APIソース (DMM/FANZA/DUGA)'),
        ),
    ]
