# Generated by Django 4.2.1 on 2026-01-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_pcattribute_options_alter_pcproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcattribute',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='検索時に使用する別名です。複数の場合はカンマ(,)で区切ってください。', verbose_name='検索キーワード'),
        ),
    ]
