# Generated by Django 4.2.1 on 2026-06-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_imageaudit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageaudit',
            options={'ordering': ['-checked_at']},
        ),
        migrations.AddField(
            model_name='imageaudit',
            name='content_length',
            field=models.BigIntegerField(blank=True, help_text='Content-Length(bytes)', null=True),
        ),
        migrations.AddField(
            model_name='imageaudit',
            name='final_url',
            field=models.URLField(blank=True, default='', help_text='リダイレクト後URL', max_length=2000),
        ),
        migrations.AlterField(
            model_name='imageaudit',
            name='checked_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='最終監査日時', null=True),
        ),
        migrations.AlterField(
            model_name='imageaudit',
            name='entity_id',
            field=models.BigIntegerField(blank=True, help_text='監査対象ID', null=True),
        ),
        migrations.AlterField(
            model_name='imageaudit',
            name='entity_type',
            field=models.CharField(db_index=True, help_text='adult_product / actress / maker 等', max_length=50),
        ),
        migrations.AlterField(
            model_name='imageaudit',
            name='failure_reason',
            field=models.TextField(blank=True, default='', help_text='失敗理由'),
        ),
        migrations.AlterField(
            model_name='imageaudit',
            name='height',
            field=models.IntegerField(blank=True, help_text='画像高さ(px)', null=True),
        ),
        migrations.AlterField(
            model_name='imageaudit',
            name='http_status',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageaudit',
            name='image_status',
            field=models.CharField(db_index=True, default='unknown', help_text='ok / placeholder / forbidden / 404 / 410 / timeout / http_xxx', max_length=50),
        ),
        migrations.AlterField(
            model_name='imageaudit',
            name='image_url',
            field=models.URLField(blank=True, help_text='元画像URL', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='imageaudit',
            name='image_valid',
            field=models.BooleanField(default=False, help_text='Frontend が参照する表示可否'),
        ),
        migrations.AlterField(
            model_name='imageaudit',
            name='product_id_unique',
            field=models.CharField(blank=True, db_index=True, default='', help_text='FANZA_xxx / DUGA_xxx 等', max_length=255),
        ),
        migrations.AlterField(
            model_name='imageaudit',
            name='width',
            field=models.IntegerField(blank=True, help_text='画像幅(px)', null=True),
        ),
        migrations.AddIndex(
            model_name='imageaudit',
            index=models.Index(fields=['entity_type', 'entity_id'], name='image_audit_entity__79044e_idx'),
        ),
        migrations.AddIndex(
            model_name='imageaudit',
            index=models.Index(fields=['image_status'], name='image_audit_image_s_a1cfe3_idx'),
        ),
        migrations.AddIndex(
            model_name='imageaudit',
            index=models.Index(fields=['http_status'], name='image_audit_http_st_3bf7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='imageaudit',
            index=models.Index(fields=['checked_at'], name='image_audit_checked_df07f6_idx'),
        ),
        migrations.AlterModelTable(
            name='imageaudit',
            table='image_audits',
        ),
    ]
