# Generated by Django 4.2.1 on 2026-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pcattribute_search_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='AI記事要約/メタ情報'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CPUモデル詳細'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='display_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ディスプレイ情報'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='gpu_model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GPUモデル詳細'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='is_ai_pc',
            field=models.BooleanField(default=False, verbose_name='AI PC該当フラグ'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='last_spec_parsed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='スペック解析実行日'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='memory_gb',
            field=models.IntegerField(blank=True, null=True, verbose_name='メモリ(GB数値)'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='npu_tops',
            field=models.FloatField(blank=True, null=True, verbose_name='NPU性能(TOPS)'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='spec_score',
            field=models.IntegerField(default=0, verbose_name='性能評価スコア(0-100)'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='storage_gb',
            field=models.IntegerField(blank=True, null=True, verbose_name='ストレージ(GB数値)'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='target_segment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AI判定ターゲット層'),
        ),
    ]
