# Generated by Django 4.2.1 on 2026-02-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_adultproduct_api_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultproduct',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adult_products_authored', to='api.author', verbose_name='著者/作者'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='AI記事要約'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='投稿済み'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='product_description',
            field=models.TextField(blank=True, help_text='AI解析の元ネタとなる文章', null=True, verbose_name='作品紹介文'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='score_cost',
            field=models.IntegerField(default=0, verbose_name='コスパ(1-100)'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='score_erotic',
            field=models.IntegerField(default=0, verbose_name='エロ(1-100)'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='score_rarity',
            field=models.IntegerField(default=0, verbose_name='希少性(1-100)'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='score_story',
            field=models.IntegerField(default=0, verbose_name='構成(1-100)'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='score_visual',
            field=models.IntegerField(default=0, verbose_name='ルックス(1-100)'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='spec_score',
            field=models.IntegerField(default=0, verbose_name='総合スコア(0-100)'),
        ),
    ]
