# Generated by Django 4.2.1 on 2026-06-02 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_imageaudit_options_imageaudit_content_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageaudit',
            name='image_status',
            field=models.CharField(db_index=True, default='unknown', help_text='Backend Authority 状態。ユーザーへ提示可能なコンテンツかを示す。ok / placeholder / forbidden / 404 / 410 / timeout / http_xxx', max_length=50),
        ),
        migrations.CreateModel(
            name='FanzaSampleMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_movie_url', models.URLField(blank=True, default='', verbose_name='Sample Movie URL')),
                ('player_url', models.URLField(blank=True, default='', verbose_name='Player URL')),
                ('html_snapshot', models.TextField(blank=True, default='', verbose_name='HTML Snapshot')),
                ('player_args_json', models.JSONField(blank=True, null=True, verbose_name='Player Args JSON')),
                ('default_mp4_url', models.TextField(blank=True, default='', verbose_name='Default MP4 URL')),
                ('related_urls', models.JSONField(blank=True, default=list, verbose_name='Related URLs')),
                ('fetch_status', models.CharField(blank=True, default='', max_length=50, verbose_name='Fetch Status')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Checked At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adult_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fanza_sample_movie', to='api.adultproduct', verbose_name='アダルト商品')),
            ],
            options={
                'verbose_name': 'FANZA Sample Movie',
                'verbose_name_plural': 'FANZA Sample Movies',
                'db_table': 'fanza_sample_movies',
            },
        ),
    ]
