# Generated by Django 4.2.1 on 2026-02-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_adultproduct_author_alter_adultproduct_ai_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adultproduct',
            options={'ordering': ['-release_date'], 'verbose_name': '統合アダルト商品', 'verbose_name_plural': '統合アダルト商品一覧'},
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='author',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='last_spec_parsed_at',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='score_cost',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='score_erotic',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='score_rarity',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='score_story',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='score_visual',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='target_segment',
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='ai_chat_comments',
            field=models.JSONField(blank=True, default=list, help_text='AIが自動生成したユーザーコメント。サイトに活気があるように見せる演出。', verbose_name='疑似チャット/掲示板'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='products_authored', to='api.author', verbose_name='著者/作家/原画'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='campaign_date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='セール終了期限'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='campaign_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='セール名'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='content_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='コンテンツID'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='delivery_type',
            field=models.CharField(blank=True, help_text='DVD, Blu-ray, streaming, 電子版(特典付) 等', max_length=50, null=True, verbose_name='媒体/形式'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='discount_rate',
            field=models.IntegerField(default=0, verbose_name='割引率(%)'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='floor_code',
            field=models.CharField(default='general', help_text='videoa(動画), unlimited_comic(読み放題), mono(通販) 等', max_length=50, verbose_name='フロア識別'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='セール中'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='is_unlimited',
            field=models.BooleanField(default=False, verbose_name='サブスク対象'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='jancode',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='JAN/ISBNコード'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='list_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='定価'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='maker_product_id',
            field=models.CharField(blank=True, help_text='パッケージに記載されている英数字', max_length=100, null=True, verbose_name='メーカー品番'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='mono_product_info',
            field=models.JSONField(blank=True, default=list, help_text='動画ページから通販ページ(DVD)へ誘導するための相互リンクデータ。', verbose_name='他フロア商品リンク'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='price_all_options',
            field=models.JSONField(blank=True, default=list, help_text='動画のHD/4K/DL版の各価格や、書籍の単体購入価格リスト。', verbose_name='価格バリエーション'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='review_average',
            field=models.FloatField(default=0.0, verbose_name='評価平均点'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='レビュー投稿数'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='rich_description',
            field=models.TextField(blank=True, help_text='HTML(__NEXT_DATA__)から抽出。AIがエロい紹介文や属性を生成するための濃厚なソース。', null=True, verbose_name='詳細ストーリー'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='sample_image_list',
            field=models.JSONField(default=list, help_text='ギャラリー表示用URLリスト', verbose_name='サンプル画像'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='stock_status',
            field=models.CharField(blank=True, help_text='通販フロア(mono)での在庫切れチェック用', max_length=50, null=True, verbose_name='在庫/予約状況'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='tachiyomi_url',
            field=models.URLField(blank=True, help_text='ブックスやPCゲームのプレビューリンク', max_length=2048, null=True, verbose_name='試し読み/体験版URL'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='unlimited_channels',
            field=models.JSONField(blank=True, default=list, help_text="['FANZAブックス読み放題', '見放題ch デラックス'] 等", verbose_name='所属サブスク名'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='volume',
            field=models.CharField(blank=True, help_text='動画の分数、書籍のページ数、ゲームの容量', max_length=50, null=True, verbose_name='総量'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='attr_type',
            field=models.CharField(choices=[('body', '身体的特徴'), ('style', '作品スタイル'), ('scene', 'シチュエーション'), ('feature', '技術・物理仕様'), ('event', '販売形態・催事')], max_length=20, verbose_name='属性タイプ'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='AIがタイトルや紹介文からこの属性を自動判定するための単語群（カンマ区切り）', verbose_name='抽出キーワード'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='actresses',
            field=models.ManyToManyField(related_name='products', to='api.actress', verbose_name='出演女優/声優'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='ai_content',
            field=models.TextField(blank=True, help_text='rich_descriptionを元にAIが書いた、読ませるためのブログ記事風文章。', null=True, verbose_name='AI生成独自レビュー'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='ai_summary',
            field=models.CharField(blank=True, help_text='一覧画面で目を引くための1行紹介文。', max_length=500, null=True, verbose_name='AIキャッチコピー'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='api_product_id',
            field=models.CharField(help_text='cidやproduct_id', max_length=255, verbose_name='元サイトの商品ID'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='api_source',
            field=models.CharField(help_text='fanza / dmm / duga', max_length=20, verbose_name='ソース元'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.adultattribute', verbose_name='AI抽出・詳細タグ'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_directed', to='api.director', verbose_name='監督'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='genres',
            field=models.ManyToManyField(related_name='products', to='api.genre', verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='image_url_list',
            field=models.JSONField(default=dict, help_text="{'small': '...', 'large': '...', 'list': '...'}。フロアによって使い分け。", verbose_name='メイン画像群'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='公開状態'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_labeled', to='api.label', verbose_name='レーベル'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_made', to='api.maker', verbose_name='メーカー/出版社'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='現在の最安値'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='product_description',
            field=models.TextField(blank=True, help_text='公式APIから取得。SEO用の基本的な説明文。', null=True, verbose_name='標準紹介文'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='product_id_unique',
            field=models.CharField(help_text='例: fanza_unlimited_b079akroe00078 (重複登録防止用)', max_length=255, unique=True, verbose_name='システム内一意識別子'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='発売・公開日'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='sample_movie_url',
            field=models.JSONField(blank=True, help_text='iframe用URLや、ビットレート別のストリーミング用JSONデータ。', null=True, verbose_name='動画プレイヤー情報'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_in_series', to='api.series', verbose_name='シリーズ'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='spec_score',
            field=models.IntegerField(default=0, help_text='評価点や売上、AI判定から算出する内部的な表示優先度。', verbose_name='おすすめスコア'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
