# Generated by Django 4.2.1 on 2026-01-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pcproduct_ai_summary_pcproduct_cpu_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='cpu_socket',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CPUソケット(推論)'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='motherboard_chipset',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='推奨チップセット'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='power_recommendation',
            field=models.IntegerField(blank=True, null=True, verbose_name='推奨電源容量(W)'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='ram_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='メモリ規格'),
        ),
    ]
