# Generated by Django 4.2.1 on 2026-06-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_imageaudit_image_status_fanzasamplemovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='strengths',
            field=models.JSONField(blank=True, default=list, verbose_name='AI判定強みポイント'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='target_user',
            field=models.TextField(blank=True, null=True, verbose_name='AI判定ターゲットユーザー詳細'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='usage_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='AI判定使用タグ'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='weaknesses',
            field=models.JSONField(blank=True, default=list, verbose_name='AI判定弱みポイント'),
        ),
    ]
