# Generated by Django 4.2.1 on 2026-02-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_adultproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultproduct',
            name='last_spec_parsed_at',
            field=models.DateTimeField(blank=True, help_text='最後にAIソムリエが解析を行った日時。', null=True, verbose_name='AI解析実施日'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='volume',
            field=models.CharField(blank=True, help_text='動画の分数、書籍의 ページ数、ゲームの容量', max_length=50, null=True, verbose_name='総量'),
        ),
    ]
