# Generated by Django 4.2.1 on 2026-01-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pcproduct_cpu_socket_pcproduct_motherboard_chipset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='device_count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='利用可能台数'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='edition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='エディション/版番'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='is_download',
            field=models.BooleanField(default=False, verbose_name='DL版フラグ'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='license_term',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ライセンス期間'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='os_support',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='対応OS詳細'),
        ),
        migrations.AlterField(
            model_name='pcattribute',
            name='attr_type',
            field=models.CharField(choices=[('cpu', 'CPU'), ('memory', 'メモリ'), ('storage', 'ストレージ'), ('gpu', 'グラフィック'), ('npu', 'AIプロセッサ(NPU)'), ('os', 'OS'), ('software', 'ソフトウェア種別'), ('license', 'ライセンス形態')], max_length=20, verbose_name='属性タイプ'),
        ),
    ]
