# Generated by Django 4.2.1 on 2026-02-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_adultproduct_last_spec_parsed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultproduct',
            name='target_segment',
            field=models.CharField(blank=True, help_text='【AIへの指示】この作品が最も刺さる層を特定してください（例：新人発掘好き、ムチムチ熟女ファン等）。', max_length=255, null=True, verbose_name='ターゲット層'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='ai_chat_comments',
            field=models.JSONField(blank=True, default=list, help_text='【AIへの指示】複数のユーザーになりきって、作品に対する期待や感想を3〜5件生成してください。', verbose_name='疑似チャット/掲示板'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='ai_content',
            field=models.TextField(blank=True, help_text='【AIへの指示】rich_descriptionを元に、読者の欲情を煽るブログ記事風レビューを生成してください。', null=True, verbose_name='AI生成独自レビュー'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='ai_summary',
            field=models.CharField(blank=True, help_text='【AIへの指示】一覧画面で目を引くための強烈な1行キャッチコピーを生成してください。', max_length=500, null=True, verbose_name='AIキャッチコピー'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='delivery_type',
            field=models.CharField(blank=True, help_text='DVD, Blu-ray, streaming等', max_length=50, null=True, verbose_name='媒体/形式'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='image_url_list',
            field=models.JSONField(default=dict, help_text="{'small': '...', 'large': '...', 'list': '...'}。", verbose_name='メイン画像群'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='mono_product_info',
            field=models.JSONField(blank=True, default=list, verbose_name='他フロア商品リンク'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='price_all_options',
            field=models.JSONField(blank=True, default=list, help_text='動画のHD/4K/DL版の各価格リスト。', verbose_name='価格バリエーション'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='sample_movie_url',
            field=models.JSONField(blank=True, null=True, verbose_name='動画プレイヤー情報'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='spec_score',
            field=models.IntegerField(default=0, help_text='評価点やAI判定から算出する内部的な表示優先度(0-100)。', verbose_name='おすすめスコア'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='stock_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='在庫/予約状況'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='tachiyomi_url',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='試し読み/体験版URL'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='volume',
            field=models.CharField(blank=True, help_text='動画の分数、書籍のページ数', max_length=50, null=True, verbose_name='総量'),
        ),
    ]
