# Generated by Django 4.2.1 on 2026-07-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pcproduct_strengths_pcproduct_target_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='spec_complete',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Specification Complete'),
        ),
    ]
