# Generated by Django 4.2.1 on 2026-01-22 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pcproduct_device_count_pcproduct_edition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='記録時価格')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='記録日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='api.pcproduct', verbose_name='対象製品')),
            ],
            options={
                'verbose_name': '価格履歴',
                'verbose_name_plural': '価格履歴一覧',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
