# Generated by Django 4.2.1 on 2026-02-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_adultproduct_target_segment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultproduct',
            name='ranking_trend',
            field=models.JSONField(blank=True, default=list, help_text='[数値, 数値...] の配列データ', verbose_name='ランキング推移'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_cost_performance',
            field=models.IntegerField(default=0, help_text='0-100', verbose_name='コストパフォーマンス'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_fetish',
            field=models.IntegerField(default=0, help_text='0-100', verbose_name='フェティシズム濃度スコア'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_story',
            field=models.IntegerField(default=0, help_text='0-100', verbose_name='シナリオ強度スコア'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_visual',
            field=models.IntegerField(default=0, help_text='0-100', verbose_name='視覚的完成度スコア'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='ai_chat_comments',
            field=models.JSONField(blank=True, default=list, help_text='【AIへの指示】複数のユーザーになりきった期待や感想。', verbose_name='疑似チャット/掲示板'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='ai_content',
            field=models.TextField(blank=True, help_text='【AIへの指示】rich_descriptionを元に、ブログ記事風レビューを生成。', null=True, verbose_name='AI生成独自レビュー'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='ai_summary',
            field=models.CharField(blank=True, help_text='【AIへの指示】一覧画面で目を引く1行キャッチコピーを生成。', max_length=500, null=True, verbose_name='AIキャッチコピー'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='target_segment',
            field=models.CharField(blank=True, help_text='【AIへの指示】この作品が最も刺さる層を特定。', max_length=255, null=True, verbose_name='ターゲット層'),
        ),
    ]
