# Generated by Django 4.2.1 on 2026-07-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_pcproduct_spec_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='spec_processed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Specification Processed'),
        ),
    ]
