# Generated by Django 4.2.1 on 2026-01-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='score_ai',
            field=models.IntegerField(default=0, verbose_name='AI・NPUスコア(1-100)'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='score_cost',
            field=models.IntegerField(default=0, verbose_name='コスパスコア(1-100)'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='score_cpu',
            field=models.IntegerField(default=0, verbose_name='CPU性能スコア(1-100)'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='score_gpu',
            field=models.IntegerField(default=0, verbose_name='GPU性能スコア(1-100)'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='score_portable',
            field=models.IntegerField(default=0, verbose_name='携帯性スコア(1-100)'),
        ),
        migrations.AlterField(
            model_name='pcproduct',
            name='spec_score',
            field=models.IntegerField(default=0, verbose_name='総合評価スコア(0-100)'),
        ),
    ]
