# Generated by Django 4.2.1 on 2026-07-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_pcproduct_spec_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='model',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='モデル名'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='pc_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='サイト商品ID'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='product_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='型番'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='発売日'),
        ),
    ]
