# Generated by Django 4.2.1 on 2026-02-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_adultproduct_ranking_trend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultproduct',
            name='api_source',
            field=models.CharField(help_text='FANZA / DMM / DUGA', max_length=20, verbose_name='ソース元'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='product_id_unique',
            field=models.CharField(help_text='例: FANZA_unlimited_b079akroe00078 (重複登録防止用)', max_length=255, unique=True, verbose_name='システム内一意識別子'),
        ),
    ]
