# Generated by Django 4.2.1 on 2026-01-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_pcproduct_score_ai_pcproduct_score_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('pv_count', models.PositiveIntegerField(default=0)),
                ('ranking_score', models.FloatField(default=0.0)),
                ('daily_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='api.pcproduct')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
