# Generated by Django 4.2.1 on 2026-02-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_adultproduct_api_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adultproduct',
            old_name='score_cost_performance',
            new_name='score_cost',
        ),
    ]
