# Generated by Django 4.2.1 on 2026-07-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_pcproduct_model_pcproduct_pc_id_pcproduct_product_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='brand',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='ブランド'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='collaboration',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='コラボレーション'),
        ),
        migrations.AddField(
            model_name='pcproduct',
            name='series',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='シリーズ'),
        ),
    ]
