# Generated by Django 4.2.1 on 2026-07-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_pcproduct_brand_pcproduct_collaboration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(db_index=True, help_text='scraping / api / ftp / file', max_length=50)),
                ('source_name', models.CharField(db_index=True, help_text='geekom / lenovo / linkshare ...', max_length=100)),
                ('document_type', models.CharField(db_index=True, help_text='product / category / listing', max_length=50)),
                ('document_key', models.CharField(db_index=True, help_text='Source内で一意となるキー', max_length=255)),
                ('source_url', models.URLField(blank=True, default='')),
                ('content_type', models.CharField(help_text='text/html, application/json ...', max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'acquisition_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='acquisitiondocument',
            constraint=models.UniqueConstraint(fields=('source_name', 'document_type', 'document_key'), name='unique_acquisition_document'),
        ),
    ]
