# Generated by Django 4.2.1 on 2026-02-15 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_score_cost_performance_adultproduct_score_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adultproduct',
            old_name='score_cost',
            new_name='score_cost_performance',
        ),
    ]
