# Generated by Django 4.2.1 on 2026-07-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_acquisitiondocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(db_index=True, max_length=100)),
                ('document_type', models.CharField(db_index=True, max_length=50)),
                ('document_key', models.CharField(db_index=True, max_length=255)),
                ('contract', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'import_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(db_index=True, max_length=100)),
                ('document_type', models.CharField(db_index=True, max_length=50)),
                ('document_key', models.CharField(db_index=True, max_length=255)),
                ('observation', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'observation_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='observationdocument',
            constraint=models.UniqueConstraint(fields=('source_name', 'document_type', 'document_key'), name='unique_observation_document'),
        ),
        migrations.AddConstraint(
            model_name='importdocument',
            constraint=models.UniqueConstraint(fields=('source_name', 'document_type', 'document_key'), name='unique_import_document'),
        ),
    ]
