# Generated by Django 4.2.1 on 2026-02-17 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_score_cost_adultproduct_score_cost_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanzaFloorMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(db_index=True, help_text='FANZA / DMM.com', max_length=50, verbose_name='サイトコード')),
                ('site_name', models.CharField(max_length=100, verbose_name='サイト名')),
                ('service_code', models.CharField(db_index=True, help_text='digital, mono, book等', max_length=50, verbose_name='サービスコード')),
                ('service_name', models.CharField(max_length=100, verbose_name='サービス名')),
                ('floor_code', models.CharField(db_index=True, help_text='videoa, dvd, comic等', max_length=50, unique=True, verbose_name='フロアコード')),
                ('floor_name', models.CharField(max_length=100, verbose_name='フロア名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='最終同期日')),
            ],
            options={
                'verbose_name': '階層マスタ',
                'verbose_name_plural': '階層マスタ一覧',
                'db_table': 'fanza_floor_master',
                'ordering': ['site_code', 'service_code', 'floor_code'],
            },
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='actresses',
            field=models.ManyToManyField(related_name='products', to='api.actress'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='ai_chat_comments',
            field=models.JSONField(blank=True, default=list, verbose_name='疑似チャット'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='ai_content',
            field=models.TextField(blank=True, null=True, verbose_name='AI生成独自レビュー'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='AIキャッチコピー'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.adultattribute'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='products_authored', to='api.author'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='媒体/形式'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_directed', to='api.director'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='floor_code',
            field=models.CharField(db_index=True, help_text='videoa(動画), unlimited_comic(読み放題), mono(通販) 等', max_length=50, verbose_name='フロア識別'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='genres',
            field=models.ManyToManyField(related_name='products', to='api.genre'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='image_url_list',
            field=models.JSONField(default=dict, verbose_name='メイン画像群'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_labeled', to='api.label'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='last_spec_parsed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI解析実施日'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_made', to='api.maker'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='maker_product_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='メーカー品番'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='price_all_options',
            field=models.JSONField(blank=True, default=list, verbose_name='価格バリエーション'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='標準紹介文'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='product_id_unique',
            field=models.CharField(help_text='例: fanza_videoa_abp123', max_length=255, unique=True, verbose_name='システム内一意識別子'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='ranking_trend',
            field=models.JSONField(blank=True, default=list, verbose_name='ランキング推移'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='rich_description',
            field=models.TextField(blank=True, null=True, verbose_name='詳細ストーリー'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='sample_image_list',
            field=models.JSONField(default=list, verbose_name='サンプル画像'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='score_cost_performance',
            field=models.IntegerField(default=0, verbose_name='コスパ'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='score_fetish',
            field=models.IntegerField(default=0, verbose_name='フェティシズム濃度'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='score_story',
            field=models.IntegerField(default=0, verbose_name='シナリオ強度'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='score_visual',
            field=models.IntegerField(default=0, verbose_name='視覚的完成度'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_in_series', to='api.series'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='spec_score',
            field=models.IntegerField(default=0, verbose_name='おすすめスコア'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='target_segment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ターゲット層'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='unlimited_channels',
            field=models.JSONField(blank=True, default=list, verbose_name='所属サブスク名'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='総量'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='floor_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.fanzafloormaster', verbose_name='所属フロアマスタ'),
        ),
    ]
