# Generated by Django 4.2.1 on 2026-02-18 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_fanzafloormaster_alter_adultproduct_actresses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adultattribute',
            options={'ordering': ['order', 'id'], 'verbose_name': 'アダルト属性', 'verbose_name_plural': 'アダルト属性'},
        ),
        migrations.RemoveField(
            model_name='adultattribute',
            name='search_keywords',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='ai_chat_comments',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='ai_content',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='ai_summary',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='campaign_date_end',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='campaign_title',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='director',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='jancode',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='last_spec_parsed_at',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='maker_product_id',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='mono_product_info',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='ranking_trend',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='score_cost_performance',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='score_fetish',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='score_story',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='score_visual',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='series',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='spec_score',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='stock_status',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='tachiyomi_url',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='target_segment',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='volume',
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='api_service',
            field=models.CharField(blank=True, help_text='digital, mono, video 等', max_length=50, null=True, verbose_name='サービス識別'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='attr_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='属性タイプ'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='name',
            field=models.CharField(max_length=100, verbose_name='属性名'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='order',
            field=models.IntegerField(default=0, verbose_name='並び順'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='api_product_id',
            field=models.CharField(max_length=255, verbose_name='元サイトの商品ID'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='api_source',
            field=models.CharField(help_text='fanza / dmm / duga', max_length=20, verbose_name='ソース元'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='content_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='discount_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='floor_code',
            field=models.CharField(db_index=True, help_text='videoa, videoc, video 等', max_length=50, verbose_name='フロア識別'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='image_url_list',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.label'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.maker'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='price_all_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='product_id_unique',
            field=models.CharField(max_length=255, unique=True, verbose_name='システム内一意識別子'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='review_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='sample_image_list',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='sample_movie_url',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='unlimited_channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='fanzafloormaster',
            name='site_code',
            field=models.CharField(db_index=True, help_text='fanza / dmm', max_length=50, verbose_name='サイトコード'),
        ),
    ]
