# Generated by Django 4.2.1 on 2026-07-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_importdocument_observationdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='observation_runtime',
            field=models.JSONField(blank=True, default=dict, verbose_name='Observation Runtime'),
        ),
    ]
