# Generated by Django 4.2.1 on 2026-08-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_pcproduct_observation_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcproduct',
            name='product_points',
            field=models.JSONField(blank=True, default=list, verbose_name='AI生成製品選択ポイント'),
        ),
    ]
