# Generated by Django 4.2.1 on 2026-02-18 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_adultattribute_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adultattribute',
            options={'ordering': ['attr_type', 'order', 'name'], 'verbose_name': '作品属性', 'verbose_name_plural': '作品属性一覧'},
        ),
        migrations.AddField(
            model_name='adultattribute',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='AIがタイトルや紹介文からこの属性を自動判定するための単語群（カンマ区切り）', verbose_name='抽出キーワード'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='ai_chat_comments',
            field=models.JSONField(blank=True, default=list, verbose_name='疑似チャット'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='ai_content',
            field=models.TextField(blank=True, null=True, verbose_name='AI生成独自レビュー'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='AIキャッチコピー'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.adultattribute'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='products_authored', to='api.author'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='campaign_date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='セール終了期限'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='campaign_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='セール名'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='媒体/形式'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_directed', to='api.director'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='jancode',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='JAN/ISBNコード'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='last_spec_parsed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI解析実施日'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='maker_product_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='メーカー品番'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='mono_product_info',
            field=models.JSONField(blank=True, default=list, verbose_name='他フロア商品リンク'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='ranking_trend',
            field=models.JSONField(blank=True, default=list, verbose_name='ランキング推移'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_cost_performance',
            field=models.IntegerField(default=0, verbose_name='コスパ'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_fetish',
            field=models.IntegerField(default=0, verbose_name='フェティシズム濃度'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_story',
            field=models.IntegerField(default=0, verbose_name='シナリオ強度'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_visual',
            field=models.IntegerField(default=0, verbose_name='視覚的完成度'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_in_series', to='api.series'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='spec_score',
            field=models.IntegerField(default=0, verbose_name='おすすめスコア'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='stock_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='在庫/予約状況'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='tachiyomi_url',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='試し読み/体験版URL'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='target_segment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ターゲット層'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='総量'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='attr_type',
            field=models.CharField(choices=[('body', '身体的特徴'), ('style', '作品スタイル'), ('scene', 'シチュエーション'), ('feature', '技術・物理仕様'), ('event', '販売形態・催事')], max_length=20, verbose_name='属性タイプ'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='name',
            field=models.CharField(max_length=100, verbose_name='表示名'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='api_service',
            field=models.CharField(blank=True, help_text='digital, mono, book等', max_length=50, null=True, verbose_name='サービス種別'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='api_source',
            field=models.CharField(max_length=20, verbose_name='ソース元'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='content_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='コンテンツID'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='discount_rate',
            field=models.IntegerField(default=0, verbose_name='割引率(%)'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='floor_code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='フロア識別'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='image_url_list',
            field=models.JSONField(default=dict, verbose_name='メイン画像群'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='セール中'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='公開状態'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_unlimited',
            field=models.BooleanField(default=False, verbose_name='サブスク対象'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_labeled', to='api.label'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_made', to='api.maker'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='現在の最安値'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='price_all_options',
            field=models.JSONField(blank=True, default=list, verbose_name='価格バリエーション'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='review_average',
            field=models.FloatField(default=0.0, verbose_name='評価平均点'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='レビュー投稿数'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='sample_image_list',
            field=models.JSONField(default=list, verbose_name='サンプル画像'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='sample_movie_url',
            field=models.JSONField(blank=True, null=True, verbose_name='動画プレイヤー情報'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='unlimited_channels',
            field=models.JSONField(blank=True, default=list, verbose_name='所属サブスク名'),
        ),
        migrations.AlterField(
            model_name='fanzafloormaster',
            name='site_code',
            field=models.CharField(db_index=True, help_text='FANZA / DMM.com', max_length=50, verbose_name='サイトコード'),
        ),
    ]
