# Generated by Django 4.2.1 on 2026-02-18 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_adultattribute_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adultproduct',
            name='mono_product_info',
        ),
        migrations.RemoveField(
            model_name='adultproduct',
            name='ranking_trend',
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_erotic',
            field=models.IntegerField(default=0, verbose_name='エロティズム(EROTIC)'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='score_rarity',
            field=models.IntegerField(default=0, verbose_name='希少性(RARITY)'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='search_keywords',
            field=models.TextField(blank=True, verbose_name='抽出キーワード'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='api_service',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='サービス種別'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='floor_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.fanzafloormaster'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='jancode',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='JANコード'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='raw_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adult_products', to='api.rawapidata'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='score_cost_performance',
            field=models.IntegerField(default=0, verbose_name='コスパ(COST)'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='score_story',
            field=models.IntegerField(default=0, verbose_name='シナリオ強度(STORY)'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='score_visual',
            field=models.IntegerField(default=0, verbose_name='視覚的完成度(VISUAL)'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='spec_score',
            field=models.IntegerField(default=0, verbose_name='おすすめ総合スコア'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='tachiyomi_url',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='試し読みURL'),
        ),
        migrations.AlterField(
            model_name='fanzafloormaster',
            name='floor_code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='フロアコード'),
        ),
    ]
