# Generated by Django 4.2.1 on 2026-02-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_adultproduct_mono_product_info_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FanzaProduct',
        ),
    ]
