# Generated by Django 4.2.1 on 2026-02-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_fanzaproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='api_source',
            field=models.CharField(max_length=10, verbose_name='APIソース'),
        ),
        migrations.AlterField(
            model_name='author',
            name='api_source',
            field=models.CharField(max_length=10, verbose_name='APIソース'),
        ),
        migrations.AlterField(
            model_name='director',
            name='api_source',
            field=models.CharField(max_length=10, verbose_name='APIソース'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='api_source',
            field=models.CharField(max_length=10, verbose_name='APIソース'),
        ),
        migrations.AlterField(
            model_name='label',
            name='api_source',
            field=models.CharField(max_length=10, verbose_name='APIソース'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='api_source',
            field=models.CharField(max_length=10, verbose_name='APIソース'),
        ),
        migrations.AlterField(
            model_name='rawapidata',
            name='api_source',
            field=models.CharField(choices=[('fanza', 'FANZA API'), ('dmm', 'DMM API'), ('duga', 'DUGA API')], max_length=10, verbose_name='APIソース'),
        ),
        migrations.AlterField(
            model_name='series',
            name='api_source',
            field=models.CharField(max_length=10, verbose_name='APIソース'),
        ),
    ]
