# Generated by Django 4.2.1 on 2026-02-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_actress_api_source_alter_author_api_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanzafloormaster',
            name='ai_system_prompt',
            field=models.TextField(blank=True, help_text='AIへの性格付け指示（例：音楽批評家風、官能的ストーリーテラー等）', null=True, verbose_name='AIシステムプロンプト'),
        ),
        migrations.AddField(
            model_name='fanzafloormaster',
            name='ai_tone_keywords',
            field=models.CharField(blank=True, help_text='AIに意識させたいキーワード、または禁止語（カンマ区切り）', max_length=255, null=True, verbose_name='トーンキーワード'),
        ),
        migrations.AddField(
            model_name='fanzafloormaster',
            name='is_adult',
            field=models.BooleanField(default=True, help_text='Trueならアダルト向け、Falseなら一般向けのトーンを適用', verbose_name='アダルトフラグ'),
        ),
    ]
