# Generated by Django 4.2.1 on 2026-02-22 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_fanzafloormaster_ai_system_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultActressProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actress_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='FANZA女優ID')),
                ('name', models.CharField(max_length=255, verbose_name='女優名')),
                ('ruby', models.CharField(blank=True, max_length=255, null=True, verbose_name='読み仮名')),
                ('bust', models.IntegerField(blank=True, null=True, verbose_name='バスト')),
                ('cup', models.CharField(blank=True, max_length=10, null=True, verbose_name='カップ')),
                ('waist', models.IntegerField(blank=True, null=True, verbose_name='ウエスト')),
                ('hip', models.IntegerField(blank=True, null=True, verbose_name='ヒップ')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='身長')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='血液型')),
                ('prefectures', models.CharField(blank=True, max_length=100, null=True, verbose_name='出身地')),
                ('hobby', models.TextField(blank=True, null=True, verbose_name='趣味')),
                ('image_url_small', models.URLField(blank=True, max_length=500, null=True, verbose_name='画像URL(小)')),
                ('image_url_large', models.URLField(blank=True, max_length=500, null=True, verbose_name='画像URL(大)')),
                ('external_links', models.JSONField(blank=True, default=dict, help_text='SNSやWikipedia、公式サイトのURLをJSON形式で保持', verbose_name='外部リンク集')),
                ('ai_catchcopy', models.CharField(blank=True, max_length=500, null=True, verbose_name='AIキャッチコピー')),
                ('ai_description', models.TextField(blank=True, null=True, verbose_name='AI生成紹介文')),
                ('score_visual', models.IntegerField(default=0, verbose_name='視覚的評価(VISUAL)')),
                ('score_style', models.IntegerField(default=0, verbose_name='スタイル評価(STYLE)')),
                ('score_performance', models.IntegerField(default=0, verbose_name='表現力(PERFORMANCE)')),
                ('score_popularity', models.IntegerField(default=0, verbose_name='市場人気度(POPULARITY)')),
                ('ai_power_score', models.IntegerField(default=0, verbose_name='おすすめ総合評価')),
                ('product_count', models.PositiveIntegerField(default=0, verbose_name='出演作品数')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='最終同期日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_actress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.actress', verbose_name='マスター女優')),
            ],
            options={
                'verbose_name': 'アダルト女優プロファイル',
                'verbose_name_plural': 'アダルト女優プロファイル一覧',
                'db_table': 'adult_actress_profile',
                'ordering': ['-ai_power_score', '-product_count'],
            },
        ),
    ]
