# Generated by Django 4.2.1 on 2026-02-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_adultactressprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultactressprofile',
            name='master_actress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.actress', verbose_name='マスター女優'),
        ),
    ]
