# Generated by Django 4.2.1 on 2026-02-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_adultactressprofile_master_actress'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultproduct',
            name='ai_catchcopy',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='AIキャッチコピー'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='ai_score_erotic',
            field=models.IntegerField(default=0, verbose_name='AI刺激評価'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='ai_score_story',
            field=models.IntegerField(default=0, verbose_name='AIストーリー評価'),
        ),
        migrations.AddField(
            model_name='adultproduct',
            name='ai_score_visual',
            field=models.IntegerField(default=0, verbose_name='AI映像評価'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='ai_summary',
            field=models.TextField(blank=True, null=True, verbose_name='AIサマリー文'),
        ),
    ]
