# Generated by Django 4.2.1 on 2026-03-02 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_adultproduct_ai_catchcopy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultproduct',
            name='has_attributes',
            field=models.BooleanField(db_index=True, default=False, help_text='検索を高速化するために、属性が1つ以上ある場合にTrueにする', verbose_name='属性あり'),
        ),
        migrations.AlterField(
            model_name='adultactressprofile',
            name='ai_power_score',
            field=models.IntegerField(db_index=True, default=0, verbose_name='おすすめ総合評価'),
        ),
        migrations.AlterField(
            model_name='adultactressprofile',
            name='cup',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='カップ'),
        ),
        migrations.AlterField(
            model_name='adultactressprofile',
            name='external_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='外部リンク集'),
        ),
        migrations.AlterField(
            model_name='adultactressprofile',
            name='height',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='身長'),
        ),
        migrations.AlterField(
            model_name='adultactressprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='adultactressprofile',
            name='master_actress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.actress'),
        ),
        migrations.AlterField(
            model_name='adultactressprofile',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='女優名'),
        ),
        migrations.AlterField(
            model_name='adultactressprofile',
            name='product_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='出演作品数'),
        ),
        migrations.AlterField(
            model_name='adultactressprofile',
            name='score_performance',
            field=models.IntegerField(db_index=True, default=0, verbose_name='表現力(PERFORMANCE)'),
        ),
        migrations.AlterField(
            model_name='adultactressprofile',
            name='score_popularity',
            field=models.IntegerField(db_index=True, default=0, verbose_name='市場人気度(POPULARITY)'),
        ),
        migrations.AlterField(
            model_name='adultactressprofile',
            name='score_style',
            field=models.IntegerField(db_index=True, default=0, verbose_name='スタイル評価(STYLE)'),
        ),
        migrations.AlterField(
            model_name='adultactressprofile',
            name='score_visual',
            field=models.IntegerField(db_index=True, default=0, verbose_name='視覚的評価(VISUAL)'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='attr_type',
            field=models.CharField(choices=[('body', '身体的特徴'), ('style', '作品スタイル'), ('scene', 'シチュエーション'), ('feature', '技術・物理仕様'), ('event', '販売形態・催事')], db_index=True, max_length=20, verbose_name='属性タイプ'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='api_service',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='サービス種別'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='api_source',
            field=models.CharField(db_index=True, max_length=20, verbose_name='ソース元'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_on_sale',
            field=models.BooleanField(db_index=True, default=False, verbose_name='セール中'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_posted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='公開状態'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='is_unlimited',
            field=models.BooleanField(db_index=True, default=False, verbose_name='サブスク対象'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='price',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='現在の最安値'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='release_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='発売・公開日'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='review_average',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='評価平均点'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='spec_score',
            field=models.IntegerField(db_index=True, default=0, verbose_name='おすすめ総合スコア'),
        ),
        migrations.AlterField(
            model_name='fanzafloormaster',
            name='ai_system_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='AIシステムプロンプト'),
        ),
        migrations.AlterField(
            model_name='fanzafloormaster',
            name='ai_tone_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='トーンキーワード'),
        ),
        migrations.AlterField(
            model_name='fanzafloormaster',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='fanzafloormaster',
            name='is_adult',
            field=models.BooleanField(default=True, verbose_name='アダルトフラグ'),
        ),
        migrations.AddIndex(
            model_name='adultactressprofile',
            index=models.Index(fields=['is_active', '-ai_power_score'], name='adult_actre_is_acti_2b7071_idx'),
        ),
        migrations.AddIndex(
            model_name='adultproduct',
            index=models.Index(fields=['is_active', 'has_attributes', '-release_date'], name='adult_produ_is_acti_2456ad_idx'),
        ),
        migrations.AddIndex(
            model_name='adultproduct',
            index=models.Index(fields=['api_source', 'is_active', '-release_date'], name='adult_produ_api_sou_821ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='adultproduct',
            index=models.Index(fields=['floor_code', 'is_active', '-release_date'], name='adult_produ_floor_c_59dc2a_idx'),
        ),
    ]
