# Generated by Django 4.2.1 on 2026-03-04 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_adultproduct_has_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ブランド名')),
                ('parent_company', models.CharField(max_length=20, verbose_name='親キャリア')),
                ('is_mvno', models.BooleanField(default=False, verbose_name='MVNOか')),
            ],
            options={
                'verbose_name': 'BSキャリア',
                'verbose_name_plural': 'BSキャリア一覧',
            },
        ),
        migrations.CreateModel(
            name='BSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='機種名')),
                ('brand', models.CharField(max_length=50, verbose_name='メーカー')),
                ('storage_gb', models.IntegerField(verbose_name='容量(GB)')),
                ('cpu_chipset', models.CharField(max_length=100, verbose_name='SoC (CPU/GPU)')),
                ('npu_performance', models.CharField(blank=True, max_length=100, verbose_name='AI(NPU)性能')),
                ('ram_gb', models.IntegerField(verbose_name='メモリ(RAM)')),
                ('display_info', models.CharField(max_length=100, verbose_name='画面 (種類/サイズ)')),
                ('refresh_rate', models.IntegerField(default=60, verbose_name='リフレッシュレート(Hz)')),
                ('has_nfc_felica', models.BooleanField(default=True, verbose_name='おサイフケータイ')),
                ('sim_free_price', models.IntegerField(verbose_name='公式直販価格')),
            ],
            options={
                'verbose_name': 'BS端末',
                'verbose_name_plural': 'BS端末一覧',
            },
        ),
        migrations.CreateModel(
            name='BSMobilePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='プラン名')),
                ('base_fee', models.IntegerField(verbose_name='基本月額(税込)')),
                ('data_gb', models.IntegerField(verbose_name='データ容量(GB)')),
                ('family_discount_step1', models.IntegerField(default=0, verbose_name='家族割(2回線)')),
                ('family_discount_step2', models.IntegerField(default=0, verbose_name='家族割(3回線以上)')),
                ('fixed_line_discount', models.IntegerField(default=0, verbose_name='光回線セット割')),
                ('card_discount', models.IntegerField(default=0, verbose_name='カード払い割引')),
                ('wp_article_id', models.IntegerField(blank=True, null=True, verbose_name='解説記事ID(WP)')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='api.bscarrier')),
            ],
            options={
                'verbose_name': 'BS通信プラン',
                'verbose_name_plural': 'BS通信プラン一覧',
            },
        ),
        migrations.CreateModel(
            name='BSDevicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(verbose_name='キャリア定価')),
                ('program_price', models.IntegerField(verbose_name='2年返却時実質価格')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bscarrier')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_prices', to='api.bsdevice')),
            ],
        ),
    ]
