# Generated by Django 4.2.1 on 2026-03-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_bscarrier_bsdevice_bsmobileplan_bsdeviceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsdevice',
            name='battery_mah',
            field=models.IntegerField(default=0, verbose_name='バッテリー(mAh)'),
        ),
        migrations.AddField(
            model_name='bsdevice',
            name='waterproof_dustproof',
            field=models.CharField(default='IP68', max_length=20, verbose_name='防水防塵'),
        ),
        migrations.AddField(
            model_name='bsdevice',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='重量(g)'),
        ),
    ]
