# Generated by Django 4.2.1 on 2026-03-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_bsdevice_battery_mah_bsdevice_waterproof_dustproof_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bsdeviceprice',
            options={'verbose_name': 'BS端末価格設定', 'verbose_name_plural': 'BS端末価格設定一覧'},
        ),
        migrations.AddField(
            model_name='bsdevice',
            name='main_image',
            field=models.URLField(blank=True, help_text='一覧等で表示するメインの画像URL', max_length=500, verbose_name='代表画像URL'),
        ),
        migrations.AlterField(
            model_name='bsdevice',
            name='npu_performance',
            field=models.CharField(blank=True, help_text='例: 35 TOPS', max_length=100, verbose_name='AI(NPU)性能'),
        ),
        migrations.AlterField(
            model_name='bsdeviceprice',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bscarrier', verbose_name='キャリア'),
        ),
        migrations.AlterField(
            model_name='bsdeviceprice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_prices', to='api.bsdevice', verbose_name='端末'),
        ),
        migrations.CreateModel(
            name='BSDeviceColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50, verbose_name='カラー名')),
                ('color_code', models.CharField(blank=True, help_text='例: #0000FF (CSS等で使用可能)', max_length=7, verbose_name='カラーコード')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='個別画像URL')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='api.bsdevice', verbose_name='対象端末')),
            ],
            options={
                'verbose_name': 'BS端末カラー',
                'verbose_name_plural': 'BS端末カラー一覧',
            },
        ),
    ]
