# Generated by Django 4.2.1 on 2026-03-10 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_bsdeviceprice_options_bsdevice_main_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('tiper', 'tiper.live'), ('avflash', 'avflash'), ('bicstation', 'bicstation'), ('saving', 'bic-saving')], db_index=True, max_length=20, verbose_name='対象サイト')),
                ('content_type', models.CharField(choices=[('post', '通常記事(Post)'), ('news', 'ニュース(News)')], db_index=True, max_length=10, verbose_name='種別')),
                ('title', models.CharField(max_length=500, verbose_name='タイトル')),
                ('body_text', models.TextField(verbose_name='本文（AI生成）')),
                ('main_image_url', models.URLField(max_length=1000, verbose_name='メイン画像URL')),
                ('source_url', models.URLField(max_length=1000, unique=True, verbose_name='取得元URL')),
                ('extra_metadata', models.JSONField(blank=True, default=dict, verbose_name='メタデータ')),
                ('is_exported', models.BooleanField(db_index=True, default=False, verbose_name='外部出力済')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '配信記事',
                'verbose_name_plural': '配信記事一覧',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'content_type', '-created_at'], name='api_article_site_11193a_idx')],
            },
        ),
    ]
