# Generated by Django 4.2.1 on 2026-03-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('post', '通常記事(Post)'), ('news', 'ニュース(News)')], db_index=True, default='post', max_length=10, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='article',
            name='site',
            field=models.CharField(db_index=True, max_length=50, verbose_name='対象サイト'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(max_length=1000, verbose_name='取得元URL'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('site', 'source_url')},
        ),
    ]
