# Generated by Django 4.2.1 on 2026-03-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_article_content_type_alter_article_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='メイン画像URL'),
        ),
    ]
