# Generated by Django 4.2.1 on 2026-03-23 02:18

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_article_main_image_url'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='idx_site_type_created',
            old_name='api_article_site_11193a_idx',
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extra_metadata'], name='idx_extra_metadata_gin'),
        ),
    ]
