# Generated by Django 4.2.1 on 2026-04-02 15:05

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rename_api_article_site_11193a_idx_idx_site_type_created_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='idx_site_type_created',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='idx_metadata_gin',
            old_name='idx_extra_metadata_gin',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='main_image_url',
        ),
        migrations.AddField(
            model_name='article',
            name='body_main',
            field=models.TextField(default='', help_text='メインサイト向けの高品質・長文記事', verbose_name='本文（メインサイト用AI生成）'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='body_satellite',
            field=models.TextField(blank=True, help_text='サテライト/SEO/被リンク用の短文・要約記事', null=True, verbose_name='本文（サテライト用AI生成）'),
        ),
        migrations.AddField(
            model_name='article',
            name='images_json',
            field=models.JSONField(blank=True, default=list, verbose_name='画像セット(JSON)'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_adult',
            field=models.BooleanField(db_index=True, default=False, verbose_name='アダルト属性'),
        ),
        migrations.AddField(
            model_name='article',
            name='show_on_main',
            field=models.BooleanField(db_index=True, default=True, verbose_name='メイン表示用'),
        ),
        migrations.AddField(
            model_name='article',
            name='show_on_satellite',
            field=models.BooleanField(db_index=True, default=False, verbose_name='サテライト表示用'),
        ),
        migrations.AddField(
            model_name='article',
            name='videos_json',
            field=models.JSONField(blank=True, default=list, verbose_name='動画セット(JSON)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='extra_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='PCスペック、出演者情報、価格等の付随データ', verbose_name='拡張メタデータ'),
        ),
        migrations.AlterField(
            model_name='article',
            name='site',
            field=models.CharField(choices=[('tiper', 'Tiper (Adult)'), ('avflash', 'AV Flash (Adult)'), ('bicstation', 'Bic Station (General)'), ('saving', 'Bic Saving (General)')], db_index=True, max_length=50, verbose_name='対象サイト'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['site', 'is_adult', 'show_on_main', '-created_at'], name='idx_site_main_delivery'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['site', 'show_on_satellite', '-created_at'], name='idx_site_sat_delivery'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['images_json'], name='idx_images_gin'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['videos_json'], name='idx_videos_gin'),
        ),
    ]
