# Generated by Django 4.2.1 on 2026-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_article_idx_site_type_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultattribute',
            name='is_adult',
            field=models.BooleanField(db_index=True, default=True, help_text='Trueに固定。Bic Station側の属性マスタ同期から除外するための識別子です。', verbose_name='アダルト属性フラグ'),
        ),
        migrations.AddField(
            model_name='pcattribute',
            name='is_adult',
            field=models.BooleanField(db_index=True, default=False, help_text='Trueの場合、Bic Station（PCサイト）の解析・表示から除外されます', verbose_name='アダルト属性フラグ'),
        ),
        migrations.AlterField(
            model_name='adultattribute',
            name='attr_type',
            field=models.CharField(choices=[('body', '身体的特徴'), ('style', '作品スタイル'), ('scene', 'シチュエーション'), ('feature', '技術・物理仕様'), ('event', '販売形態・催事'), ('actor_type', '出演者タイプ')], db_index=True, max_length=20, verbose_name='属性タイプ'),
        ),
        migrations.AlterField(
            model_name='adultproduct',
            name='has_attributes',
            field=models.BooleanField(db_index=True, default=False, help_text='属性が1つ以上ある場合にTrue。検索高速化用。', verbose_name='属性あり'),
        ),
        migrations.AlterField(
            model_name='pcattribute',
            name='attr_type',
            field=models.CharField(choices=[('cpu', 'CPU'), ('memory', 'メモリ'), ('storage', 'ストレージ'), ('gpu', 'グラフィック'), ('npu', 'AIプロセッサ(NPU)'), ('os', 'OS'), ('software', 'ソフトウェア種別'), ('license', 'ライセンス形態'), ('actor_type', '出演者タイプ'), ('genre', '作品ジャンル')], max_length=20, verbose_name='属性タイプ'),
        ),
    ]
