# Generated by Django 4.2.1 on 2026-04-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_adultattribute_is_adult_pcattribute_is_adult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkshareproduct',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=2048, null=True, verbose_name='商品画像URL'),
        ),
        migrations.AddIndex(
            model_name='linkshareproduct',
            index=models.Index(fields=['sku'], name='normal_prod_sku_idx'),
        ),
    ]
