# Generated by Django 4.2.1 on 2026-04-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_linkshareproduct_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkshareapiproduct',
            name='campaign_tag',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='キャンペーンタグ'),
        ),
        migrations.AddField(
            model_name='linkshareapiproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
