# Generated by Django 4.2.1 on 2026-04-20 22:59

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_linkshareapiproduct_campaign_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('bicstation', 'Bic Station (Tech/General)'), ('saving', 'Bic Saving (Life/General)'), ('tiper', 'Tiper (Adult/Portal)'), ('avflash', 'AV Flash (Adult/News)')], db_index=True, max_length=50, verbose_name='配信対象ドメイン')),
                ('is_adult', models.BooleanField(db_index=True, default=False, verbose_name='アダルト属性')),
                ('is_pub', models.BooleanField(db_index=True, default=False, verbose_name='公開状態')),
                ('content_type', models.CharField(choices=[('post', '通常記事(Post)'), ('course', '連載/講座(Course)'), ('news', 'ニュース(News)')], db_index=True, default='post', max_length=10, verbose_name='コンテンツ種別')),
                ('series_slug', models.SlugField(help_text='例: software-fortress', max_length=100, verbose_name='連載スラグ')),
                ('phase_title', models.CharField(blank=True, help_text='例: 第1段階：OS・基盤環境の最適化', max_length=255, verbose_name='フェーズ名')),
                ('episode_no', models.IntegerField(db_index=True, default=0, verbose_name='エピソード番号')),
                ('title', models.CharField(max_length=500, verbose_name='タイトル')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URLスラグ')),
                ('body_md', models.TextField(help_text='Gemini等が生成したMarkdownをそのまま保存。表示側でパースします。', verbose_name='本文(Markdown)')),
                ('excerpt', models.TextField(blank=True, help_text='AIが前後の文脈を理解するための要約データ', max_length=2000, verbose_name='要約/AI学習用コンテキスト')),
                ('images_json', models.JSONField(blank=True, default=list, verbose_name='画像リソース(JSON)')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='拡張メタデータ')),
                ('ai_trace', models.JSONField(blank=True, default=dict, verbose_name='AI生成履歴')),
                ('category', models.CharField(db_index=True, max_length=100, verbose_name='カテゴリ')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='タグ(カンマ区切り)')),
                ('is_reviewed', models.BooleanField(db_index=True, default=False, verbose_name='検閲済み')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '統合コンテンツハブ記事',
                'verbose_name_plural': '統合コンテンツハブ記事一覧',
                'db_table': 'content_hubs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'is_adult', 'is_pub', 'episode_no'], name='idx_hub_delivery_v5'), models.Index(fields=['series_slug', 'episode_no'], name='idx_hub_series_v5'), django.contrib.postgres.indexes.GinIndex(fields=['extra_data'], name='idx_hub_extra_gin'), django.contrib.postgres.indexes.GinIndex(fields=['images_json'], name='idx_hub_img_gin')],
                'unique_together': {('site', 'series_slug', 'episode_no')},
            },
        ),
    ]
