# Generated by Django 4.2.1 on 2026-04-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_contenthub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('affiliate_url', models.URLField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(default=0)),
                ('ranking_score', models.FloatField(default=0)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('maker', models.CharField(blank=True, max_length=255)),
                ('label_name', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_adult', models.BooleanField(db_index=True, default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actresses', models.ManyToManyField(blank=True, related_name='unified_products', to='api.actress')),
                ('genres', models.ManyToManyField(blank=True, related_name='unified_products', to='api.genre')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='api_product_is_acti_b97ca3_idx'), models.Index(fields=['source'], name='api_product_source_cf909d_idx'), models.Index(fields=['is_adult'], name='api_product_is_adul_550680_idx'), models.Index(fields=['is_visible'], name='api_product_is_visi_2e8b50_idx'), models.Index(fields=['is_active', 'is_visible', 'is_adult', '-ranking_score'], name='idx_product_ranking')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_source_external_id'),
        ),
    ]
