# Generated by Django 4.2.1 on 2026-04-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_product_product_unique_source_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products_items', to='api.pcattribute'),
        ),
        migrations.AlterField(
            model_name='pcproduct',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='pc_products', to='api.pcattribute', verbose_name='スペック属性タグ'),
        ),
    ]
