# Generated by Django 4.2.1 on 2026-04-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_product_attributes_alter_pcproduct_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='affiliate_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
