# Generated by Django 4.2.1 on 2026-04-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_product_affiliate_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_fetched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='image_local',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_source',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
