# Generated by Django 4.2.1 on 2026-04-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_product_image_fetched_product_image_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique_id',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
