# Generated by Django 4.2.1 on 2026-04-29 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_product_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pc_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.pcproduct'),
        ),
    ]
