"""
Django settings for tiper_api project.
Generated by 'django-admin startproject' using Django 5.2.

💡 SHIN-VPS 統合開発環境用 カスタマイズ版
- WhiteNoiseによる静的ファイル配信
- Traefik経由のローカルアクセス許可
- 起動時の自動 collectstatic ロジック搭載（無限ループ防止版）
- PCProduct / API 連携最適化
- カスタムユーザーモデル (api.User) 搭載済み
"""

import os
import sys
from pathlib import Path
from datetime import timedelta

# プロジェクト内のパスを BASE_DIR / 'subdir' の形式で構築します。
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------------------------------
# 🔐 シークレット設定 (環境変数から読み込み)
# ----------------------------------------------------
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-default-key-please-change-in-prod')

# 💡 ローカル開発時は True、本番・ステージングは環境変数で切り替え
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ----------------------------------------------------
# ホスト / CORS / CSRF 設定
# ----------------------------------------------------
ALLOWED_HOSTS = [
    'stg.tiper.live', 'stg.bic-saving.com', 'stg.bicstation.com', 'stg.avflash.xyz', 'stg.blog.tiper.live',
    'tiper.live', 'bic-saving.com', 'bicstation.com', 'avflash.xyz', 'blog.tiper.live',
    'django-v2', 'localhost', '127.0.0.1', '*'
]

# CORS設定 (ブラウザからNext.jsを通じてAPIを叩くために必要)
CORS_ALLOWED_ORIGINS = [ 
    "https://stg.tiper.live", "https://stg.bic-saving.com", "https://stg.bicstation.com",
    "https://stg.avflash.xyz", "https://stg.blog.tiper.live",
    "https://tiper.live", "https://bic-saving.com", "https://bicstation.com",
    "https://avflash.xyz", "https://blog.tiper.live",
    "http://localhost:3000", "http://localhost:8080", "http://localhost:8083",
    "http://127.0.0.1:8083", "http://host.docker.internal",
]

# CSRFトークンを信頼するオリジン
CSRF_TRUSTED_ORIGINS = [
    'https://stg.tiper.live', 'https://stg.bic-saving.com', 'https://stg.bicstation.com',
    'https://stg.avflash.xyz', 'https://stg.blog.tiper.live',
    'https://tiper.live', 'https://bic-saving.com', 'https://bicstation.com',
    'https://avflash.xyz', 'https://blog.tiper.live',
    'http://localhost:8083', 'http://127.0.0.1:8083', 'http://host.docker.internal', 
]

# ----------------------------------------------------
# アプリケーション定義
# ----------------------------------------------------
INSTALLED_APPS = [
    'corsheaders', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'django_filters', 
    'rest_framework', 
    'rest_framework_simplejwt', 
    'django_extensions',
    'scrapers', 
    'api.apps.ApiConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tiper_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tiper_api.wsgi.application'

# ----------------------------------------------------
# データベース設定 (PostgreSQL)
# ----------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'tiper_db'),
        'USER': os.environ.get('DB_USER', 'tiper_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '1492nabe'),
        'HOST': os.environ.get('DB_HOST', 'postgres-db-v2'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# ----------------------------------------------------
# 👤 カスタムユーザーモデル設定
# ----------------------------------------------------
AUTH_USER_MODEL = 'api.User'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# ----------------------------------------------------
# 国際化
# ----------------------------------------------------
LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'
USE_I18N = True
USE_TZ = True

# ----------------------------------------------------
# 静的ファイル (WhiteNoise)
# ----------------------------------------------------
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# STORAGES = {
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#     },
# }
# ✅ 修正後 (シンプルな配信モードに変更)
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.StaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ====================================================
# API 関連の設定
# ====================================================
API_CONFIG = {
    'DUGA': {
        'API_ID': os.environ.get('DUGA_API_ID', 'dummy_duga_id'),
        'API_KEY': os.environ.get('DUGA_AFFILIATE_ID', 'dummy_aff_id'), 
        'API_URL': os.environ.get('DUGA_API_URL', 'http://affapi.duga.jp/search'),
        'TOTAL_LIMIT': int(os.environ.get('DUGA_TOTAL_LIMIT', 1000)),
    },   
    'FANZA': {
        'API_ID': os.environ.get('FANZA_API_ID', 'dummy_fanza_id'),
        'API_KEY': os.environ.get('FANZA_AFFILIATE_ID', 'dummy_fanza_aff_id'),
        'API_URL': os.environ.get('FANZA_API_URL', 'https://api.dmm.com/affiliate/v3/ItemList'),
        'TOTAL_LIMIT': int(os.environ.get('FANZA_TOTAL_LIMIT', 1000)),
    },
}

# ====================================================
# DRF 設定 (🚨 重要修正: JWT認証を有効化)
# ====================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication', # 👈 トークン認証をメインに
        # 'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', # 👈 デフォルトで認証が必要な設定に
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10, 
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ),
}

# 💡 JWTの詳細設定を追加
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ====================================================
# ロギング設定
# ====================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'api_formatter': {
            'format': '[{levelname}] {asctime} ({name}): {message}',
            'style': '{', 'datefmt': '%H:%M:%S',
        },
    },
    'handlers': {
        'console': { 'class': 'logging.StreamHandler', 'formatter': 'api_formatter' },
    },
    'root': { 'handlers': ['console'], 'level': 'WARNING' },
    'loggers': {
        'django': { 'handlers': ['console'], 'level': 'INFO', 'propagate': False },
        'api_utils': { 'handlers': ['console'], 'level': 'DEBUG', 'propagate': False },
    }
}

# =====================================================================
# 🚀 自動 collectstatic 実行ロジック
# =====================================================================
if DEBUG and 'collectstatic' not in sys.argv:
    if 'runserver' in sys.argv or 'manage.py' in sys.argv[0]:
        import subprocess
        if not os.path.exists(STATIC_ROOT) or not os.listdir(STATIC_ROOT):
            print("🛠️ [AUTO-INFO] staticfiles not found. Running collectstatic...")
            try:
                subprocess.run(["python3", "manage.py", "collectstatic", "--noinput"], check=True)
                print("✅ [AUTO-INFO] collectstatic completed successfully.")
            except Exception as e:
                print(f"⚠️ [AUTO-ERROR] Failed to run collectstatic: {e}")