"""
Django settings for tiper_api project.

Generated by 'django-admin startproject' using Django 5.2.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

import os
from pathlib import Path

# プロジェクト内のパスを BASE_DIR / 'subdir' の形式で構築します。
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - 本番環境には不向きです
# 詳細は https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/ を参照してください

# ----------------------------------------------------
# 🔐 シークレット設定 (環境変数から読み込み)
# ----------------------------------------------------
# SECURITY WARNING: 本番環境で使用するシークレットキーは秘密にしてください!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-default-key-please-change-in-prod')

# SECURITY WARNING: 本番環境では DEBUG を True にして実行しないでください!
DEBUG = True

# ----------------------------------------------------
# ホスト / CORS / CSRF 設定
# ----------------------------------------------------
ALLOWED_HOSTS = [
    'stg.tiper.live', 
    'stg.bic-saving.com',
    'stg.bicstation.com',
    'stg.avflash.xyz',
    'stg.blog.tiper.live',
    'django-v2',  # 💡 Docker 内部ネットワーク経由のアクセスを明示的に許可
    'localhost',
    '127.0.0.1',
    '*' # 開発中は便宜上'*'のままでも動作しますが、本番ではドメインを厳定してください
]

# CORS設定
CORS_ALLOWED_ORIGINS = [ 
    "https://stg.tiper.live",
    "https://stg.bic-saving.com",
    "https://stg.bicstation.com",
    "https://stg.avflash.xyz",
    "https://stg.blog.tiper.live",
    "http://localhost:3000", # Next.js 開発用
    "http://localhost:8080",
    "http://host.docker.internal",
    "http://127.0.0.1:8080",
]

# CSRFトークンを信頼するオリジン
CSRF_TRUSTED_ORIGINS = [
    'https://stg.tiper.live',
    'https://stg.bic-saving.com',
    'https://stg.bicstation.com',
    'https://stg.avflash.xyz',
    'https://stg.blog.tiper.live',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'http://host.docker.internal', 
]


# ----------------------------------------------------
# アプリケーション定義
# ----------------------------------------------------

INSTALLED_APPS = [
    # 💡 corsheaders はミドルウェアのためにできるだけ上に配置
    'corsheaders', 
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # サードパーティ製アプリ
    'rest_framework', 
    'django_extensions', # ← show_urls を使うために追加
    'scrapers',  # ここが抜けていると「No installed app...」になります
    
    
    # 自分のアプリ 下記のように書き換えた
    'api.apps.ApiConfig',
]

MIDDLEWARE = [
    # ⚠️ CORSミドルウェアはできるだけ上に配置
    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 💡 ここに追加！
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tiper_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # 💡 BASE_DIR (/django/) の中にある api/templates を明示的に指定
            BASE_DIR / 'api' / 'templates',
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tiper_api.wsgi.application'


# ----------------------------------------------------
# データベース設定 (PostgreSQL)
# ----------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'tiper_db'),
        'USER': os.environ.get('DB_USER', 'tiper_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '1492nabe'),
        'HOST': os.environ.get('DB_HOST', 'postgres-db-v2'), # docker-compose のサービス名に一致させる
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# パスワード検証
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# ----------------------------------------------------
# 国際化
# ----------------------------------------------------
LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'
USE_I18N = True
USE_TZ = True


# 静的ファイル (CSS, JavaScript, 画像)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# デフォルトの主キー
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ====================================================
# 💡 追加: API 関連の設定
# ====================================================
API_CONFIG = {
    'DUGA': {
        'API_ID': os.environ.get('DUGA_API_ID', 'dummy_duga_id'),
        'API_KEY': os.environ.get('DUGA_AFFILIATE_ID', 'dummy_aff_id'), 
        'API_URL': os.environ.get('DUGA_API_URL', 'http://affapi.duga.jp/search'),
        'TOTAL_LIMIT': int(os.environ.get('DUGA_TOTAL_LIMIT', 1000)),
    },
    'FANZA': {
        'API_ID': os.environ.get('FANZA_API_ID', 'dummy_fanza_id'),
        'API_KEY': os.environ.get('FANZA_AFFILIATE_ID', 'dummy_fanza_aff_id'),
        'API_URL': os.environ.get('FANZA_API_URL', 'https://api.dmm.com/affiliate/v3/ItemList'),
        'TOTAL_LIMIT': int(os.environ.get('FANZA_TOTAL_LIMIT', 1000)),
    },
}

# ====================================================
# 💡 追加: DRF 設定
# ====================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    
    # ページネーション設定 (Limit & Offset 方式)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20, 
}


# ====================================================
# 💡 追加: ロギング設定 (LOGGING)
# ====================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'api_formatter': {
            'format': '[{levelname}] {asctime} ({name}): {message}',
            'style': '{',
            'datefmt': '%H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'api_formatter',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'api_utils': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}