// This file is auto-generated by the build process. Do not edit this file directly.
// Copyright (c) 2024 Shin Corporation. All rights reserved.

/* =========================================
🔥 Detail
========================================= */
export * from './detail'
